# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartDialog.ui'
#
# Created: Mon Oct 28 23:10:39 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StartDialog(object):
    def setupUi(self, StartDialog):
        StartDialog.setObjectName(_fromUtf8("StartDialog"))
        StartDialog.resize(502, 602)
        StartDialog.setStyleSheet(_fromUtf8("QDialog#StartDialog{\n"
"background-image: url(:/TestMode/startBack.jpg);}\n"
"QWidget{background-color: rgba(0, 0, 0, 0);}\n"
"QLabel{font: 75 24pt \"Adobe Arabic\";\n"
"color: rgb(255, 0, 0);}\n"
"QPushButton{font: 75 24pt \"Adobe Arabic\";\n"
"color: rgb(0, 255, 255);}\n"
"QPushButton:hover{font: 75 24pt \"Adobe Arabic\";\n"
"color: rgb(255, 255, 0);}"))
        self.okBtn = QtGui.QPushButton(StartDialog)
        self.okBtn.setGeometry(QtCore.QRect(440, 545, 50, 50))
        self.okBtn.setStyleSheet(_fromUtf8("QPushButton{border-image: url(:/TestMode/exit0.png);}\n"
"QPushButton:hover{\n"
"border-image: url(:/TestMode/exit1.png);}"))
        self.okBtn.setText(_fromUtf8(""))
        self.okBtn.setObjectName(_fromUtf8("okBtn"))
        self.gridLayoutWidget = QtGui.QWidget(StartDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 441, 527))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button6 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        self.button6.setMinimumSize(QtCore.QSize(162, 47))
        self.button6.setObjectName(_fromUtf8("button6"))
        self.gridLayout.addWidget(self.button6, 5, 0, 1, 1)
        self.button7 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        self.button7.setMinimumSize(QtCore.QSize(162, 47))
        self.button7.setObjectName(_fromUtf8("button7"))
        self.gridLayout.addWidget(self.button7, 6, 0, 1, 1)
        self.button2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        self.button2.setMinimumSize(QtCore.QSize(162, 47))
        self.button2.setObjectName(_fromUtf8("button2"))
        self.gridLayout.addWidget(self.button2, 1, 0, 1, 1)
        self.button3 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        self.button3.setMinimumSize(QtCore.QSize(162, 47))
        self.button3.setObjectName(_fromUtf8("button3"))
        self.gridLayout.addWidget(self.button3, 2, 0, 1, 1)
        self.button9 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        self.button9.setMinimumSize(QtCore.QSize(162, 47))
        self.button9.setObjectName(_fromUtf8("button9"))
        self.gridLayout.addWidget(self.button9, 8, 0, 1, 1)
        self.button8 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        self.button8.setMinimumSize(QtCore.QSize(162, 47))
        self.button8.setObjectName(_fromUtf8("button8"))
        self.gridLayout.addWidget(self.button8, 7, 0, 1, 1)
        self.button10 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button10.sizePolicy().hasHeightForWidth())
        self.button10.setSizePolicy(sizePolicy)
        self.button10.setMinimumSize(QtCore.QSize(162, 47))
        self.button10.setObjectName(_fromUtf8("button10"))
        self.gridLayout.addWidget(self.button10, 9, 0, 1, 1)
        self.button4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        self.button4.setMinimumSize(QtCore.QSize(162, 47))
        self.button4.setObjectName(_fromUtf8("button4"))
        self.gridLayout.addWidget(self.button4, 3, 0, 1, 1)
        self.button1 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        self.button1.setMinimumSize(QtCore.QSize(162, 47))
        self.button1.setObjectName(_fromUtf8("button1"))
        self.gridLayout.addWidget(self.button1, 0, 0, 1, 1)
        self.button5 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        self.button5.setMinimumSize(QtCore.QSize(162, 47))
        self.button5.setObjectName(_fromUtf8("button5"))
        self.gridLayout.addWidget(self.button5, 4, 0, 1, 1)
        self.label2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 1, 1, 1, 1)
        self.label1 = QtGui.QLabel(self.gridLayoutWidget)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 0, 1, 1, 1)
        self.label4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 3, 1, 1, 1)
        self.label5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.gridLayout.addWidget(self.label5, 4, 1, 1, 1)
        self.label3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 1, 1, 1)
        self.label8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label8.setObjectName(_fromUtf8("label8"))
        self.gridLayout.addWidget(self.label8, 7, 1, 1, 1)
        self.label7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label7.setObjectName(_fromUtf8("label7"))
        self.gridLayout.addWidget(self.label7, 6, 1, 1, 1)
        self.label6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.gridLayout.addWidget(self.label6, 5, 1, 1, 1)
        self.label10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label10.setObjectName(_fromUtf8("label10"))
        self.gridLayout.addWidget(self.label10, 9, 1, 1, 1)
        self.label9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label9.setObjectName(_fromUtf8("label9"))
        self.gridLayout.addWidget(self.label9, 8, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 5)
        self.loadAiBtn = QtGui.QPushButton(StartDialog)
        self.loadAiBtn.setGeometry(QtCore.QRect(370, 545, 50, 50))
        self.loadAiBtn.setStyleSheet(_fromUtf8("QPushButton{\n"
"border-image: url(:/TestMode/openAi0.png);}\n"
"QPushButton:hover{\n"
"border-image: url(:/TestMode/openAi1.png);}"))
        self.loadAiBtn.setText(_fromUtf8(""))
        self.loadAiBtn.setObjectName(_fromUtf8("loadAiBtn"))
        self.aiPathEdit = QtGui.QLineEdit(StartDialog)
        self.aiPathEdit.setGeometry(QtCore.QRect(10, 555, 311, 31))
        self.aiPathEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255, 200);"))
        self.aiPathEdit.setObjectName(_fromUtf8("aiPathEdit"))

        self.retranslateUi(StartDialog)
        QtCore.QMetaObject.connectSlotsByName(StartDialog)

    def retranslateUi(self, StartDialog):
        StartDialog.setWindowTitle(_translate("StartDialog", "Dialog", None))
        self.okBtn.setToolTip(_translate("StartDialog", "退出", None))
        self.okBtn.setWhatsThis(_translate("StartDialog", "退出", None))
        self.button6.setToolTip(_translate("StartDialog", "开始第六关", None))
        self.button6.setWhatsThis(_translate("StartDialog", "开始第六关", None))
        self.button6.setText(_translate("StartDialog", "第六关", None))
        self.button7.setToolTip(_translate("StartDialog", "开始第七关", None))
        self.button7.setWhatsThis(_translate("StartDialog", "开始第七关", None))
        self.button7.setText(_translate("StartDialog", "第七关", None))
        self.button2.setToolTip(_translate("StartDialog", "开始第二关", None))
        self.button2.setWhatsThis(_translate("StartDialog", "开始第二关", None))
        self.button2.setText(_translate("StartDialog", "第二关", None))
        self.button3.setToolTip(_translate("StartDialog", "开始第三关", None))
        self.button3.setWhatsThis(_translate("StartDialog", "开始第三关", None))
        self.button3.setText(_translate("StartDialog", "第三关", None))
        self.button9.setToolTip(_translate("StartDialog", "开始第九关", None))
        self.button9.setWhatsThis(_translate("StartDialog", "开始第九关", None))
        self.button9.setText(_translate("StartDialog", "第九关", None))
        self.button8.setToolTip(_translate("StartDialog", "开始第八关", None))
        self.button8.setWhatsThis(_translate("StartDialog", "开始第八关", None))
        self.button8.setText(_translate("StartDialog", "第八关", None))
        self.button10.setToolTip(_translate("StartDialog", "开始第十关", None))
        self.button10.setWhatsThis(_translate("StartDialog", "开始第十关", None))
        self.button10.setText(_translate("StartDialog", "第十关", None))
        self.button4.setToolTip(_translate("StartDialog", "开始第四关", None))
        self.button4.setWhatsThis(_translate("StartDialog", "开始第四关", None))
        self.button4.setText(_translate("StartDialog", "第四关", None))
        self.button1.setToolTip(_translate("StartDialog", "开始第一关", None))
        self.button1.setWhatsThis(_translate("StartDialog", "开始第一关", None))
        self.button1.setText(_translate("StartDialog", "第一关", None))
        self.button5.setToolTip(_translate("StartDialog", "开始第五关", None))
        self.button5.setWhatsThis(_translate("StartDialog", "开始第五关", None))
        self.button5.setText(_translate("StartDialog", "第五关", None))
        self.label2.setText(_translate("StartDialog", "TextLabel", None))
        self.label1.setText(_translate("StartDialog", "TextLabel", None))
        self.label4.setText(_translate("StartDialog", "TextLabel", None))
        self.label5.setText(_translate("StartDialog", "TextLabel", None))
        self.label3.setText(_translate("StartDialog", "label3", None))
        self.label8.setText(_translate("StartDialog", "TextLabel", None))
        self.label7.setText(_translate("StartDialog", "TextLabel", None))
        self.label6.setText(_translate("StartDialog", "TextLabel", None))
        self.label10.setText(_translate("StartDialog", "TextLabel", None))
        self.label9.setText(_translate("StartDialog", "TextLabel", None))
        self.loadAiBtn.setToolTip(_translate("StartDialog", "载入AI", None))
        self.loadAiBtn.setWhatsThis(_translate("StartDialog", "载入AI", None))

import test_TestMode_rc
