# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part_humanvsai.ui'
#
# Created: Sun Oct 06 17:35:51 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HumanvsAi(object):
    def setupUi(self, HumanvsAi):
        HumanvsAi.setObjectName(_fromUtf8("HumanvsAi"))
        HumanvsAi.resize(1024, 684)
        self.backFrame = QtGui.QFrame(HumanvsAi)
        self.backFrame.setGeometry(QtCore.QRect(0, 0, 1021, 681))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.backFrame.setFont(font)
        self.backFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.backFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.backFrame.setObjectName(_fromUtf8("backFrame"))
        self.returnButton = QtGui.QPushButton(self.backFrame)
        self.returnButton.setGeometry(QtCore.QRect(30, 20, 40, 40))
        self.returnButton.setText(_fromUtf8(""))
        self.returnButton.setObjectName(_fromUtf8("returnButton"))
        self.helpButton = QtGui.QPushButton(self.backFrame)
        self.helpButton.setGeometry(QtCore.QRect(110, 20, 40, 40))
        self.helpButton.setText(_fromUtf8(""))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.aiButton = QtGui.QPushButton(self.backFrame)
        self.aiButton.setGeometry(QtCore.QRect(10, 480, 40, 40))
        self.aiButton.setText(_fromUtf8(""))
        self.aiButton.setObjectName(_fromUtf8("aiButton"))
        self.info_ai = QtGui.QLineEdit(self.backFrame)
        self.info_ai.setGeometry(QtCore.QRect(60, 480, 141, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_ai.sizePolicy().hasHeightForWidth())
        self.info_ai.setSizePolicy(sizePolicy)
        self.info_ai.setAutoFillBackground(False)
        self.info_ai.setReadOnly(True)
        self.info_ai.setObjectName(_fromUtf8("info_ai"))
        self.mapButton = QtGui.QPushButton(self.backFrame)
        self.mapButton.setGeometry(QtCore.QRect(10, 550, 40, 40))
        self.mapButton.setText(_fromUtf8(""))
        self.mapButton.setObjectName(_fromUtf8("mapButton"))
        self.info_map = QtGui.QLineEdit(self.backFrame)
        self.info_map.setGeometry(QtCore.QRect(60, 560, 141, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_map.sizePolicy().hasHeightForWidth())
        self.info_map.setSizePolicy(sizePolicy)
        self.info_map.setObjectName(_fromUtf8("info_map"))
        self.startButton = QtGui.QPushButton(self.backFrame)
        self.startButton.setGeometry(QtCore.QRect(10, 610, 40, 40))
        self.startButton.setText(_fromUtf8(""))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.backFrame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(220, 90, 591, 511))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.backFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(830, 120, 181, 431))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.playerLabel = QtGui.QLabel(self.backFrame)
        self.playerLabel.setGeometry(QtCore.QRect(830, 70, 161, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.playerLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimHei"))
        font.setPointSize(20)
        self.playerLabel.setFont(font)
        self.playerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerLabel.setObjectName(_fromUtf8("playerLabel"))
        self.label = QtGui.QLabel(self.backFrame)
        self.label.setGeometry(QtCore.QRect(50, 70, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("SimHei"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.roundLabel = QtGui.QLabel(self.backFrame)
        self.roundLabel.setGeometry(QtCore.QRect(430, 10, 161, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roundLabel.sizePolicy().hasHeightForWidth())
        self.roundLabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.roundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.roundLabel.setFont(font)
        self.roundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roundLabel.setObjectName(_fromUtf8("roundLabel"))
        self.errorLabel = QtGui.QLabel(self.backFrame)
        self.errorLabel.setGeometry(QtCore.QRect(330, 60, 400, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorLabel.setPalette(palette)
        self.errorLabel.setText(_fromUtf8(""))
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName(_fromUtf8("errorLabel"))

        self.retranslateUi(HumanvsAi)
        QtCore.QMetaObject.connectSlotsByName(HumanvsAi)

    def retranslateUi(self, HumanvsAi):
        HumanvsAi.setWindowTitle(_translate("HumanvsAi", "Form", None))
        self.playerLabel.setText(_translate("HumanvsAi", "Player", None))
        self.label.setText(_translate("HumanvsAi", "AI", None))
        self.roundLabel.setText(_translate("HumanvsAi", "Round 0", None))

