# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part_replayer.ui'
#
# Created: Sat Oct 05 19:12:33 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Replayer(object):
    def setupUi(self, Replayer):
        Replayer.setObjectName(_fromUtf8("Replayer"))
        Replayer.resize(1024, 751)
        Replayer.setMaximumSize(QtCore.QSize(166664, 166664))
        self.noSoundButton = QtGui.QPushButton(Replayer)
        self.noSoundButton.setGeometry(QtCore.QRect(20, 40, 40, 40))
        self.noSoundButton.setText(_fromUtf8(""))
        self.noSoundButton.setCheckable(False)
        self.noSoundButton.setObjectName(_fromUtf8("noSoundButton"))
        self.soundButton = QtGui.QPushButton(Replayer)
        self.soundButton.setGeometry(QtCore.QRect(80, 40, 40, 40))
        self.soundButton.setText(_fromUtf8(""))
        self.soundButton.setCheckable(False)
        self.soundButton.setObjectName(_fromUtf8("soundButton"))
        self.loadFileButton = QtGui.QPushButton(Replayer)
        self.loadFileButton.setGeometry(QtCore.QRect(140, 40, 40, 40))
        self.loadFileButton.setText(_fromUtf8(""))
        self.loadFileButton.setCheckable(False)
        self.loadFileButton.setObjectName(_fromUtf8("loadFileButton"))
        self.horizontalLayoutWidget = QtGui.QWidget(Replayer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 170, 821, 481))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.replayLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.replayLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.replayLayout.setMargin(0)
        self.replayLayout.setObjectName(_fromUtf8("replayLayout"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Replayer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(370, 660, 491, 42))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.preStepButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preStepButton.sizePolicy().hasHeightForWidth())
        self.preStepButton.setSizePolicy(sizePolicy)
        self.preStepButton.setMinimumSize(QtCore.QSize(40, 40))
        self.preStepButton.setMaximumSize(QtCore.QSize(40, 40))
        self.preStepButton.setAutoFillBackground(True)
        self.preStepButton.setText(_fromUtf8(""))
        self.preStepButton.setObjectName(_fromUtf8("preStepButton"))
        self.horizontalLayout.addWidget(self.preStepButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.playBackwardButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBackwardButton.sizePolicy().hasHeightForWidth())
        self.playBackwardButton.setSizePolicy(sizePolicy)
        self.playBackwardButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playBackwardButton.setMaximumSize(QtCore.QSize(40, 40))
        self.playBackwardButton.setAutoFillBackground(True)
        self.playBackwardButton.setText(_fromUtf8(""))
        self.playBackwardButton.setCheckable(True)
        self.playBackwardButton.setObjectName(_fromUtf8("playBackwardButton"))
        self.horizontalLayout.addWidget(self.playBackwardButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pauseButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pauseButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pauseButton.setAutoFillBackground(True)
        self.pauseButton.setText(_fromUtf8(""))
        self.pauseButton.setCheckable(True)
        self.pauseButton.setObjectName(_fromUtf8("pauseButton"))
        self.horizontalLayout.addWidget(self.pauseButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.rePlayButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rePlayButton.sizePolicy().hasHeightForWidth())
        self.rePlayButton.setSizePolicy(sizePolicy)
        self.rePlayButton.setMinimumSize(QtCore.QSize(40, 40))
        self.rePlayButton.setMaximumSize(QtCore.QSize(40, 40))
        self.rePlayButton.setAutoFillBackground(True)
        self.rePlayButton.setText(_fromUtf8(""))
        self.rePlayButton.setObjectName(_fromUtf8("rePlayButton"))
        self.horizontalLayout.addWidget(self.rePlayButton)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.endPlayButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endPlayButton.sizePolicy().hasHeightForWidth())
        self.endPlayButton.setSizePolicy(sizePolicy)
        self.endPlayButton.setMinimumSize(QtCore.QSize(40, 40))
        self.endPlayButton.setMaximumSize(QtCore.QSize(40, 40))
        self.endPlayButton.setAutoFillBackground(True)
        self.endPlayButton.setText(_fromUtf8(""))
        self.endPlayButton.setObjectName(_fromUtf8("endPlayButton"))
        self.horizontalLayout.addWidget(self.endPlayButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.playForwardButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playForwardButton.sizePolicy().hasHeightForWidth())
        self.playForwardButton.setSizePolicy(sizePolicy)
        self.playForwardButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playForwardButton.setMaximumSize(QtCore.QSize(40, 40))
        self.playForwardButton.setAutoFillBackground(True)
        self.playForwardButton.setText(_fromUtf8(""))
        self.playForwardButton.setCheckable(True)
        self.playForwardButton.setObjectName(_fromUtf8("playForwardButton"))
        self.horizontalLayout.addWidget(self.playForwardButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.nextStepButton = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextStepButton.sizePolicy().hasHeightForWidth())
        self.nextStepButton.setSizePolicy(sizePolicy)
        self.nextStepButton.setMinimumSize(QtCore.QSize(40, 40))
        self.nextStepButton.setMaximumSize(QtCore.QSize(40, 40))
        self.nextStepButton.setAutoFillBackground(True)
        self.nextStepButton.setText(_fromUtf8(""))
        self.nextStepButton.setObjectName(_fromUtf8("nextStepButton"))
        self.horizontalLayout.addWidget(self.nextStepButton)
        self.roundLabel = QtGui.QLabel(Replayer)
        self.roundLabel.setGeometry(QtCore.QRect(530, 110, 141, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roundLabel.sizePolicy().hasHeightForWidth())
        self.roundLabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.roundLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.roundLabel.setFont(font)
        self.roundLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.roundLabel.setObjectName(_fromUtf8("roundLabel"))

        self.retranslateUi(Replayer)
        QtCore.QMetaObject.connectSlotsByName(Replayer)

    def retranslateUi(self, Replayer):
        Replayer.setWindowTitle(_translate("Replayer", "Replayer", None))
        self.roundLabel.setText(_translate("Replayer", "Round 0", None))

